all:	
	mkdir bin
	cp src/symtab.py bin/
	cp src/parser.py bin/
	cp src/lexer.py bin/
	cp src/tac.py bin/
	cp src/irgen bin/
	chmod 777 bin/*
	chmod +x bin/*
clean:
	rm -r bin/
	rm parser.out
	rm parsetab.py